Fix unit tests on hosts where /tmp is on a separate device
Hardlinking across different devices cannot be done. Thus the test fails like
this:

--- FAIL: TestPreload (0.00s)
    gettext_test.go:103: link testdata/en/messages.mo /tmp/gogettext333580384/en/LC_MESSAGES/messages.mo: invalid cross-device link
FAIL
FAIL    github.com/snapcore/go-gettext  0.003s
ok      github.com/snapcore/go-gettext/pluralforms      0.008s

Signed-off-by: Maciek Borzecki <maciek.borzecki@gmail.com>